import 'package:flutter_bloc/flutter_bloc.dart';
import '../../domain/repositories/annotation_repository.dart';
import '../../domain/entities/annotation.dart';
import 'annotation_event.dart';
import 'annotation_state.dart';

/// BLoC for managing annotation state and operations
class AnnotationBloc extends Bloc<AnnotationEvent, AnnotationState> {
  final AnnotationRepository _repository;

  AnnotationBloc({required AnnotationRepository repository})
      : _repository = repository,
        super(AnnotationInitial()) {
    on<LoadAnnotationsEvent>(_onLoadAnnotations);
    on<AddAnnotationEvent>(_onAddAnnotation);
    on<UpdateAnnotationEvent>(_onUpdateAnnotation);
    on<DeleteAnnotationEvent>(_onDeleteAnnotation);
    on<SearchAnnotationsEvent>(_onSearchAnnotations);
  }

  /// Handle loading annotations for a file
  Future<void> _onLoadAnnotations(
    LoadAnnotationsEvent event,
    Emitter<AnnotationState> emit,
  ) async {
    emit(AnnotationLoading());
    try {
      final annotations = await _repository.getAnnotationsForFile(event.filePath);
      emit(AnnotationLoaded(annotations, filePath: event.filePath));
    } catch (e) {
      emit(AnnotationError('Failed to load annotations: ${e.toString()}'));
    }
  }

  /// Handle adding a new annotation
  Future<void> _onAddAnnotation(
    AddAnnotationEvent event,
    Emitter<AnnotationState> emit,
  ) async {
    try {
      // Create annotation (ID will be generated by service)
      final annotation = Annotation(
        id: '', // Will be generated
        filePath: event.filePath,
        anchorText: event.anchorText,
        lineNumber: event.lineNumber,
        content: event.content,
        color: event.color,
        createdAt: DateTime.now(),
        tags: event.tags,
      );

      await _repository.saveAnnotation(annotation);

      // Reload annotations for the file
      final annotations = await _repository.getAnnotationsForFile(event.filePath);
      emit(AnnotationOperationSuccess('Annotation added', annotations));
    } catch (e) {
      emit(AnnotationError('Failed to add annotation: ${e.toString()}'));
    }
  }

  /// Handle updating an annotation
  Future<void> _onUpdateAnnotation(
    UpdateAnnotationEvent event,
    Emitter<AnnotationState> emit,
  ) async {
    try {
      await _repository.updateAnnotation(event.annotation);

      // Reload annotations for the file
      final annotations = await _repository.getAnnotationsForFile(event.annotation.filePath);
      emit(AnnotationOperationSuccess('Annotation updated', annotations));
    } catch (e) {
      emit(AnnotationError('Failed to update annotation: ${e.toString()}'));
    }
  }

  /// Handle deleting an annotation
  Future<void> _onDeleteAnnotation(
    DeleteAnnotationEvent event,
    Emitter<AnnotationState> emit,
  ) async {
    try {
      await _repository.deleteAnnotation(event.filePath, event.annotationId);

      // Reload annotations for the file
      final annotations = await _repository.getAnnotationsForFile(event.filePath);
      emit(AnnotationOperationSuccess('Annotation deleted', annotations));
    } catch (e) {
      emit(AnnotationError('Failed to delete annotation: ${e.toString()}'));
    }
  }

  /// Handle searching annotations
  Future<void> _onSearchAnnotations(
    SearchAnnotationsEvent event,
    Emitter<AnnotationState> emit,
  ) async {
    emit(AnnotationLoading());
    try {
      final annotations = await _repository.searchAnnotations(event.query);
      emit(AnnotationLoaded(annotations));
    } catch (e) {
      emit(AnnotationError('Failed to search annotations: ${e.toString()}'));
    }
  }
}
